let tableJsonFile = [
  {
    eventName: "JOLTS Job Openings",
    currency: "usd",
    startDate: "03-12-2024, __09:00 pm",
    id: "01",
    actual: "7.74M",
    forecast: "7.51M",
    previous: "7.37M",
    point: "+ 0.14",
    colour: "up",
    mPredict: "up",
    imgLink: [
      "https://drive.google.com/file/d/1v87D8sR4Jr04mvX62UdUgLP3R_UVIjzp/view?usp=sharing",
      "https://drive.google.com/file/d/1vcKMFktsN6k1-YrlJayub0N3i5-12Uz_/view?usp=sharing",
      "https://drive.google.com/file/d/1zzV1xWfyCAaeA4_6cnsZzwYs-sGeExsx/view?usp=sharing",
    ],
  },
  {
    eventName: "CPI m/m",
    currency: "usd",
    startDate: "11-12-2024, __07:30 pm",
    id: "02",
    actual: "0.3%",
    forecast: "0.3%",
    previous: "0.2%",
    point: "+ 0.1%",
    colour: "up",
    mPredict: "up",
    imgLink: [
      "https://drive.google.com/file/d/18k_I2aRBAQp3tWBq4tWwqPZu1A0dy0j5/view?usp=sharing",
      "https://drive.google.com/file/d/1yil6uDWQGHRjJfbUKcZAs-BAkPTid85z/view?usp=sharing",
      "https://drive.google.com/file/d/10mCThLmdFriUdM6lRnzeVYLfZ791L_ln/view?usp=sharing",
      "https://drive.google.com/file/d/1nfkA79lAzgzBrouH86DR0uNilJGv3KgL/view?usp=sharing",
    ],
  },
  {
    eventName: "CPI y/y",
    currency: "usd",
    startDate: "11-12-2024, __07:30 pm",
    id: "02",
    actual: "2.7%",
    forecast: "2.7%",
    previous: "2.6%",
    point: "+ 0.1%",
    colour: "up",
    mPredict: "up",
    imgLink: [
      "https://drive.google.com/file/d/18k_I2aRBAQp3tWBq4tWwqPZu1A0dy0j5/view?usp=sharing",
      "https://drive.google.com/file/d/1yil6uDWQGHRjJfbUKcZAs-BAkPTid85z/view?usp=sharing",
      "https://drive.google.com/file/d/10mCThLmdFriUdM6lRnzeVYLfZ791L_ln/view?usp=sharing",
      "https://drive.google.com/file/d/1nfkA79lAzgzBrouH86DR0uNilJGv3KgL/view?usp=sharing",
    ],
  },
];
